services:
  - type: web
    name: jewellery-backend
    env: node
    region: singapore
    plan: free
    buildCommand: npm install && npx prisma migrate deploy
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
